### ISSUE TITLE
H2 database cant not list table when in `Postgres` mode

### ISSUE THREAD

**Issue by ciusji** [GuinsooLab/console#16]
Function "col_description" not found; SQL statement: select ns.nspname as table_schema, cls.relname as table_name, attr.attname as column_name, trim(leading '_' from tp.typname) as data_type, pg_catalog.col_description(attr.attrelid, attr.attnum) as column_description from pg_catalog.pg_attribute as attr join pg_catalog.pg_class as cls on cls.oid = attr.attrelid join pg_catalog.pg_namespace as ns on ns.oid = cls.relnamespace join pg_catalog.pg_type as tp on tp.typelem = attr.atttypid where cls.relkind in ('r', 'v', 'm', 'f') and ns.nspname not in ('pg_catalog', 'pg_toast', 'information_schema') and not attr.attisdropped and attr.attnum > 0 order by ns.nspname, cls.relname, attr.attnum limit 1000001 [90022-214]

**Comment by ciusji** [comment]
H2 database in Postgres mode instance:  jdbc:h2:~/test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH

**Comment by ciusji** [comment]
We will comment the col_description function formally when connecting in Postgres dialect, below is the visit SQL

```select 
    ns.nspname as table_schema, 
    cls.relname as table_name, 
    attr.attname as column_name,
    trim(leading '_' from tp.typname) as data_type
// fixed by ciusji, issue link: https://github.com/GuinsooLab/console/issues/16     
// pg_catalog.col_description(attr.attrelid, attr.attnum) as column_description
  from 
    pg_catalog.pg_attribute as attr
    join pg_catalog.pg_class as cls on cls.oid = attr.attrelid
    join pg_catalog.pg_namespace as ns on ns.oid = cls.relnamespace
    join pg_catalog.pg_type as tp on tp.typelem = attr.atttypid
  where 
    cls.relkind in ('r', 'v', 'm', 'f')
    and ns.nspname not in ('pg_catalog', 'pg_toast', 'information_schema')
    and not attr.attisdropped 
    and attr.attnum > 0
  order by 
    ns.nspname,
    cls.relname,
    attr.attnum
```

**Comment by 306labs** [comment]
🚀

**Comment by 306labs** [comment]
But we could't view comment in left bar then add comment to postgres schema
